'use client';

import './globals.scss';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { ReactNode } from 'react';
import SidebarContainer from './components/SidebarMenu/SidebarMenu';

const mont = Montserrat({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={mont.className}>
        <SidebarContainer />
        {children}
      </body>
    </html>
  );
}
