'use client';

import './globals.scss';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { ReactNode } from 'react';
import { DeskTopSidebar } from './components/SidebarMenu/SidebarMenu';

export const mont = Montserrat({ subsets: ['latin'] });
export const sx = { sx: { fontFamily: mont.style.fontFamily } };

const metadata: Metadata = {
  title: 'Rick Morty App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={mont.className} suppressHydrationWarning={true}>
        <DeskTopSidebar />
        {children}
      </body>
    </html>
  );
}
